version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moviesite
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_DATABASE=test-db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres
    networks:
      - application
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000

networks:
  application:
    driver: bridge
